spring.application.name=styleFactory
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.eeygssltkhvyhijixvgn
spring.datasource.password=60pwHhG1jfJ1Nv6z
#spring.datasource.url=jdbc:postgresql://localhost:5432/styleFactory
#spring.datasource.username=postgres
#spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=404a635266556a586e3272357538782f413f4428472b4b6250655368566d5971
jwt.expiration=86400000

